// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqrybqosgzwipslciqke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcnlicW9zZ3p3aXBzbGNpcWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODE1MjYsImV4cCI6MjA1ODI1NzUyNn0.8JMyzro23ogcOsRmeyr6qcn9c3Jv5b9Xc-wrEF06N6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);